//
// Created by J Chen on 2025/8/30.
//

#ifndef AUTUMNLOG_SRC_WRITER_CONSOLE_WRITER_H_
#define AUTUMNLOG_SRC_WRITER_CONSOLE_WRITER_H_

class ConsoleWriter {};

#endif  // AUTUMNLOG_SRC_WRITER_CONSOLE_WRITER_H_
